name: Publish VSCode Extension

# on:
#   push:
#     tags:
#       - "v*"
on:
  workflow_run:
    workflows: ["Release Please"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Compile TypeScript
        run: npm run compile

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
